# Warning: this name must stay in sync with the badges referenced in the README
name: 'tests MinGW'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  mingw:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Start a 64 bit Mingw environment
          update: true
          install: >-
            openssl

      - name: Install dependencies
        run: |
          pacman -S --noconfirm --needed git make mingw-w64-x86_64-{toolchain,ffmpeg,python,python3-pillow,meson,glslang,vulkan-devel,python-certifi}

      - name: Build
        run: |
          export REQUESTS_CA_BUNDLE='python -m certifi'
          export SSL_CERT_FILE='python -m certifi'
          ./configure.py
          make

      - name: Python import and dylib runtime test
        run: |
          . venv/bin/activate
          python -c 'import pynodegl, pynodegl_utils'
          ngl-python -h
